
#ifndef DATATYPE_H
#define DATATYPE_H
    #include<stdio.h>
    #include<stdlib.h>
    #include<string.h>
    #include<math.h>
    #include <stdarg.h>

    typedef void*              GENERIC;
    typedef char*              STRING;
    typedef double*            FLOAT;
    typedef short int*         SHRINT;
    typedef long long int*     LINT;
    #define MAX_VARGS          10

    typedef enum { TYPE_INT, TYPE_FLOAT, TYPE_STRING,TYPE_GENERIC,TYPE_SHORT } TYPE;
    
    typedef enum Method{Push,Pop,Mid,End,Begin,Swap,Sum,Substract,Division,Avarage,Min,Max,Mod,Multiply,Count}METH;
    
    GENERIC GAlloc(size_t Size,TYPE T);
    FLOAT FAlloc(size_t size);
    SHRINT SHAlloc(size_t size);
    STRING STAlloc(size_t size);
    LINT LINAlloc(size_t size);
    
    GENERIC GENERICPUSH(GENERIC *PTR,GENERIC VALUE);
    GENERIC GENERICPOP(GENERIC *PTR,GENERIC VALUE);
    GENERIC GENERICMID(GENERIC *PTR);
    GENERIC GENERICEND(GENERIC *PTR);
    GENERIC GENERICBEGIN(GENERIC *PTR);
    GENERIC GENERICSWAP(GENERIC *PTR,GENERIC *PTR2);
    GENERIC GENERICSUM(GENERIC *PTR);
    GENERIC GENERICSUBSTRACT(GENERIC *PTR);
    GENERIC GENERICDIVISION(GENERIC *PTR);
    GENERIC GENERICAVARAGE(GENERIC *PTR);
    GENERIC GENERICMIN(GENERIC *PTR);
    GENERIC GENERICMAX(GENERIC *PTR);
    GENERIC GENERICMOD(GENERIC *PTR);
    GENERIC GENERICMULTIPLY(GENERIC *PTR);
    GENERIC GENERICCOUNT(GENERIC *PTR);

    STRING STRINGPUSH(STRING *PTR,STRING VALUE);
    STRING STRINGPOP(STRING *PTR,STRING VALUE);
    STRING STRINGMID(STRING *PTR);
    STRING STRINGEND(STRING *PTR);
    STRING STRINGBEGIN(STRING *PTR);
    STRING STRINGMID(STRING *PTR);
    STRING STRINGSWAP(STRING *PTR,STRING *PTR2);
    STRING STRINGSUM(STRING *PTR);
    STRING STRINGSUBSTRACT(STRING *PTR);
    STRING STRINGDIVISION(STRING *PTR);
    STRING STRINGAVARAGE(STRING *PTR);
    STRING STRINGMIN(STRING *PTR);
    STRING STRINGMAX(STRING *PTR);
    STRING STRINGMOD(STRING *PTR);
    STRING STRINGMULTIPLY(STRING *PTR);
    STRING STRINGCOUNT(STRING *PTR);

    FLOAT FLOATPUSH(FLOAT *PTR, FLOAT VALUE);
    FLOAT FLOATPOP(FLOAT *PTR, FLOAT VALUE);
    FLOAT FLOATMID(FLOAT *PTR);
    FLOAT FLOATEND(FLOAT *PTR);
    FLOAT FLOATBEGIN(FLOAT *PTR);
    FLOAT FLOATSWAP(FLOAT *PTR, FLOAT *PTR2);
    FLOAT FLOATSUM(FLOAT *PTR);
    FLOAT FLOATSUBSTRACT(FLOAT *PTR);
    FLOAT FLOATDIVISION(FLOAT *PTR);
    FLOAT FLOATAVARAGE(FLOAT *PTR);
    FLOAT FLOATMIN(FLOAT *PTR);
    FLOAT FLOATMAX(FLOAT *PTR);
    FLOAT FLOATMOD(FLOAT *PTR);
    FLOAT FLOATMULTIPLY(FLOAT *PTR);
    FLOAT FLOATCOUNT(FLOAT *PTR);

    SHRINT SHRINTPUSH(SHRINT *PTR, SHRINT VALUE);
    SHRINT SHRINTPOP(SHRINT *PTR, SHRINT VALUE);
    SHRINT SHRINTMID(SHRINT *PTR);
    SHRINT SHRINTEND(SHRINT *PTR);
    SHRINT SHRINTBEGIN(SHRINT *PTR);
    SHRINT SHRINTSWAP(SHRINT *PTR, SHRINT *PTR2);
    SHRINT SHRINTSUM(SHRINT *PTR);
    SHRINT SHRINTSUBSTRACT(SHRINT *PTR);
    SHRINT SHRINTDIVISION(SHRINT *PTR);
    SHRINT SHRINTAVARAGE(SHRINT *PTR);
    SHRINT SHRINTMIN(SHRINT *PTR);
    SHRINT SHRINTMAX(SHRINT *PTR);
    SHRINT SHRINTMOD(SHRINT *PTR);
    SHRINT SHRINTMULTIPLY(SHRINT *PTR);
    SHRINT SHRINTCOUNT(SHRINT *PTR);

    LINT LINTPUSH(LINT *PTR, LINT VALUE);
    LINT LINTPOP(LINT *PTR, LINT VALUE);
    LINT LINTMID(LINT *PTR);
    LINT LINTEND(LINT *PTR);
    LINT LINTBEGIN(LINT *PTR);
    LINT LINTSWAP(LINT *PTR, LINT *PTR2);
    LINT LINTSUM(LINT *PTR);
    LINT LINTSUBSTRACT(LINT *PTR);
    LINT LINTDIVISION(LINT *PTR);
    LINT LINTAVARAGE(LINT *PTR);
    LINT LINTMIN(LINT *PTR);
    LINT LINTMAX(LINT *PTR);
    LINT LINTMOD(LINT *PTR);
    LINT LINTMULTIPLY(LINT *PTR);
    LINT LINTCOUNT(LINT *PTR);

    


    

#endif